name: Update Citations Badge

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 0 点运行一次
  workflow_dispatch:

jobs:
  update-badge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install requests beautifulsoup4

    - name: Run scraper 10 times
      run: |
        for i in {1..10}
        do
          echo "Run #$i"
          python update_scholar.py
        done

    - name: Commit and push
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add citations.json
        git commit -m "Update citations badge" || echo "No changes to commit"
        git push
